target 'iOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'SDWebImageSwiftUI'
  pod 'GoogleSignIn'

end